///////////////////////////////////////////////////////////
//  Vozac.cs
//  Implementation of the Class Vozac
//  Generated by Enterprise Architect
//  Created on:      23-Jul-2018 11:19:18 AM
//  Original author: Mihailo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace GSPPackage.Models
{
    [Table("DriverTable"),DataContract]
	public class Vozac {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity),DataMember]
        public int ID { get; set; }
        //public int LinijaID { get; set; }
        [DataMember]
        public string Ime { get; set; }
        [DataMember]
        public string Prezime { get; set; }
        [DataMember]
        public string Oznaka { get; set; }
        public Vozac(){

		}

		~Vozac(){

		}


    }//end Vozac

}//end namespace GSP